version: '3'

services:
  trojan-panel-mariadb:
    image: mariadb:10.7.3
    container_name: trojan-panel-mariadb
    restart: always
    network_mode: host
    environment:
      MYSQL_DATABASE: trojan_panel_db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      TZ: Asia/Shanghai
    volumes:
      - "${VPS_ROOT}/tpdata/mariadb/data:/var/lib/mysql"
      - "${VPS_ROOT}/tpdata/mariadb/logs:/var/log/mysql"
      - "${VPS_ROOT}/tpdata/mariadb/conf.d:/etc/mysql/conf.d"
    command: --port=9507

  trojan-panel-redis:
    image: redis:6.2.7
    container_name: trojan-panel-redis
    restart: always
    network_mode: host
    volumes:
      - "${VPS_ROOT}/tpdata/redis/data:/data"
      - "${VPS_ROOT}/tpdata/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
      - --requirepass ${REDIS_PASSWORD}
      - --port 6378

  trojan-panel:
    image: jonssonyan/trojan-panel
    container_name: trojan-panel
    restart: always
    network_mode: host
    volumes:
      - "${VPS_ROOT}/tpdata/web/:/tpdata/trojan-panel/webfile/"
      - "${VPS_ROOT}/tpdata/trojan-panel/logs/:/tpdata/trojan-panel/logs/"
      - "${VPS_ROOT}/tpdata/trojan-panel/export:/tpdata/trojan-panel/export"
      - "${VPS_ROOT}/tpdata/trojan-panel/template:/tpdata/trojan-panel/template"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=127.0.0.1"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${DB_PASSWORD}"
      - "redis_host=127.0.0.1"
      - "redis_port=6378"
      - "redis_pass=${REDIS_PASSWORD}"
      - "server_port=8081"

  trojan-panel-ui:
    image: jonssonyan/trojan-panel-ui
    container_name: trojan-panel-ui
    restart: always
    network_mode: host
    volumes:
      - "${VPS_ROOT}/tpdata/trojan-panel-ui/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "${VPS_ROOT}/ssl/:/VPS/ssl/"

  trojan-panel-core:
    image: jonssonyan/trojan-panel-core
    container_name: trojan-panel-core
    restart: always
    network_mode: host
    volumes:
      - "${VPS_ROOT}/tpdata/trojan-panel-core/bin/xray/config:/tpdata/trojan-panel-core/bin/xray/config"
      - "${VPS_ROOT}/tpdata/trojan-panel-core/bin/trojango/config:/tpdata/trojan-panel-core/bin/trojango/config"
      - "${VPS_ROOT}/tpdata/trojan-panel-core/bin/hysteria/config:/tpdata/trojan-panel-core/bin/hysteria/config"
      - "${VPS_ROOT}/tpdata/trojan-panel-core/bin/naiveproxy/config:/tpdata/trojan-panel-core/bin/naiveproxy/config"
      - "${VPS_ROOT}/tpdata/trojan-panel-core/logs/:/tpdata/trojan-panel-core/logs/"
      - "${VPS_ROOT}/tpdata/trojan-panel-core/config/sqlite/:/tpdata/trojan-panel-core/config/sqlite/"
      - "${VPS_ROOT}/ssl/:/VPS/ssl/"
      - "${VPS_ROOT}/tpdata/web/:/VPS/tpdata/web/"
      - "/etc/localtime:/etc/localtime"
    environment:
      - "GIN_MODE=release"
      - "mariadb_ip=127.0.0.1"
      - "mariadb_port=9507"
      - "mariadb_user=root"
      - "mariadb_pas=${DB_PASSWORD}"
      - "database=trojan_panel_db"
      - "account-table=account"
      - "redis_host=127.0.0.1"
      - "redis_port=6378"
      - "redis_pass=${REDIS_PASSWORD}"
      - "crt_path=${VPS_ROOT}/ssl/server.cer"
      - "key_path=${VPS_ROOT}/ssl/server.key"
      - "grpc_port=8100"
      - "server_port=8082"
